apiVersion: v1
kind: Service
metadata:
  name: data-loader-service
  namespace: yitzchakdamen-dev
  labels:
    app: data-loader
spec:
  selector:
    app: data-loader
  ports:
    - port: 8888
      targetPort: 8888
  clusterIP: None 