apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
spec:
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
      - name: data-loader
        image: yitzchakdamen/data_loadr:v2
        imagePullPolicy: Always
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: database-connection-variables-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: database-connection-variables-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  database-connection-variables-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-connection-variables-configmap
              key: DB_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: database-connection-variables-configmap
              key: APP_PORT
        ports:
        - containerPort: 8888


